### ISSUE TITLE
Consider changing from `docker-compose` to `docker compose` in your command calls

### ISSUE THREAD

**Issue by iperdomo** [gethop-dev/hop-cli#17]
> From the end of June 2023 Compose V1 won’t be supported anymore and will be removed from all Docker Desktop versions.
> Make sure you switch to [Compose V2](https://docs.docker.com/compose/compose-file/) with the `docker compose` CLI plugin or by activating the Use Docker Compose V2 setting in Docker Desktop. For more information, see the [Evolution of Compose](https://docs.docker.com/compose/compose-v2/)

Source: https://docs.docker.com/compose/

I found an issue trying to use the short/long option names `-T` vs `--no-TTY` in Github Actions
See: 
- https://github.com/orgs/community/discussions/26683
- https://github.com/yvant-coop/docker-compose-exec-test

**Comment by iarenaza** [comment]
The newly released 0.1.13 version is compatible with `docker compose` (thus v2) and `docker-compose` (v1). We've kept the v1 compatibility for the time being, because people running "stable" Linux distributions (like Debian, or Ubuntu LTS versions) only have v1 by default (if they install the packages coming from their distributions, as opposed to installing directly from the vendor).
