### ISSUE TITLE
Provide more details about Cloudformation stack creation failures

### ISSUE THREAD

**Issue by iarenaza** [gethop-dev/hop-cli#6]
Regarding getting more information from Cloudformation stack creation, it seems that we are discarding this piece of information from the API:

    StackStatusReason -> (string)
    Success/failure message associated with the stack status.

Use that value to provide more useful and meaningful errors in that stage of the bootstrapping process.

**Comment by lucassousaf** [comment]
After checking this for a while I came to the conclusion that this is more elaborated than I thought. The `StackStatusReason` will only give us enough information about the root stack, but not about nested stacks. For example, if we create the `hop-account` stack, and it fails mid-way, we'll only get the `StackStatusReason` of the rollback action which just tells us that it failed to create the resources. If we want to really have more information we'll need to rely on [`DescribeStackEvents`](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_DescribeStackEvents.html). 

This API will list the events we see in the AWS Cloudformation console. And it contains useful information such as the `ResourceStatusReason`. It's the same as the `StackStatusReason` but on an AWS resource level. However, this is not quite enough because sometimes that resource is another stack. In this case the `ResourceStatusReason` will just tell us that the stack failed to create some resource. So in order to get the real error, we would need to get the `PhysicalResourceId` from the event response (which is the ARN of the nested stack) we are interested in and do `DescribeStackEvents` using the `PysicalResourceId`. 

We can easily filter the events by `ResourceType`, `ResourceStatus`, and `ResourceStatusReason`. Normally when the creation of some resource fails Cloudformation will stop the creation of other resources and set their `ResourceStatusReason` to `Resource creation cancelled.`, which we can also use to filter out things we don't want.

NOTE: looks like the `DescribeStackEvents` API does not support any filters, so when I say "we can filter" we have to do it in our side, by code. And the event listing is also paginated after 1MB response length.

**Comment by lucassousaf** [comment]
Implemented in 4ba3f1b.
